### ISSUE TITLE
Translating MathSpring pages

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#15]
We should translate all MathSpring content.
Instead of waiting for someone to do the translation, go ahead and use Google Translate.
When there are errors, I will fix directly in the database afterwards.

--Ivon

**Comment by IvonArroyo** [comment]
The MathSpring logo: I am not clear if the **M**ATH**S**PRING word is text or if it is an image.
We could translate that logo everywhere to: **C**ULTIVANDO**M**ATEMATICA

**Comment by nsmenon** [comment]
This is a logo image. Sort of symbol. Ideally this should not be
translated. As in "Google" or "Yahoo" remains the same in all languages.

--
Neeraj

**Comment by nsmenon** [comment]
Login Page is completed. Changes should be automatically built today and
available by tomorrow.

--
Neeraj

**Comment by nsmenon** [comment]
Done The with Teachers Menu changes. Closing this for now.
