### ISSUE TITLE
Default values for parameters associated to the topic behavior 

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#19]
Mastery = 0.95  as default
Max number of problems (in a topic)= 30 as default
Max time in a topic = 30 minutes

**Comment by IvonArroyo** [comment]
Mastery = 0.95  as default
Max number of problems (in a topic)= 30 as default
Max time in a topic = 30 minutes (place it in milliseconds?)
Min number of problems in a topic = 4

**Comment by nsmenon** [comment]
Already addressed in an earlier fixed bug of setting default values in a class
