### ISSUE TITLE
Create Class: Default values for topic settings.

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#23]
When a new class is created, some default values are assigned regarding the behavior of topics. 
The screen attached is from the Old Teacher Tools, where these parameters were configured manually. While I don't want to have that ability in the new teacher tools, as maybe it is too much for teachers to manage, the default values set are not good right now. Let's please change the default values to be:

Max number of problems per topic = 40
Min number of problems per topic = 2
Max time in topic (minutes) = 30 --minutes
Min time in topic (minutes) = 0 minutes
Content failure threshold = 5 problems
Desired Topic Mastery = 0.95
Difficulty Rate = 2

The rest can be ignored/omitted, if there is anything else.

--Ivon

<img width="904" alt="screen shot 2018-12-17 at 12 40 08 pm" src="https://user-images.githubusercontent.com/5631787/50104866-202fd180-01f9-11e9-8846-84058bed3d52.png">

**Comment by IvonArroyo** [comment]
Neeraj, right now, a lot of these values are set to zero, which means it makes MathSpring not work when a user gets in. It is becoming a higher priority.

**Comment by nsmenon** [comment]
Fixed. Updated the default class creation to said values
