### ISSUE TITLE
Create Spanish Characters Lucas and Juana

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#29]
Do a search for the words 'Jake' or 'Jane' in the code and you will find where the classes for each character are. It should be a small class.

Create two classes one for each character, Juana and Lucas.

--Ivon

**Comment by IvonArroyo** [comment]
If you need to create something like JuanaFullEmpathy, or LucasFullEmpathy, to make pedagogies 1 or 2 work with these new characters, that is alright.

**Comment by nsmenon** [comment]
Done. Code for Lucas is Merged.
