### ISSUE TITLE
Delete math problem data from this student

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#32]
This one is not erasing the student data.
This is in the Manage students tab

**Comment by nsmenon** [comment]
The functionality is apparently designed to delete student data in event log table and not student information. It basically executes following two queries.

deletePracticeHutEvents
 -> delete from eventlog where studid=? and action in(every action)

resetStudentPracticeHut
->delete from studenttopicmastery where studId=?

**Comment by nsmenon** [comment]
Fixed
