### ISSUE TITLE
Please look at problem 1847

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#33]
There are several answers as possible correct answers, it is a short answer problem.
Note this is a math problem on rose right now.

However, it is only taking the first answer as a correct response, even though the answers are recorded as correct.

select * from problemanswers
where probId=1847

Why is the problem player only taking the first answer as valid?

Thanks for looking into this.

**Comment by nsmenon** [comment]
The space is causing problem while checking answer. The following snippet is called while checking for answers

  public boolean grade (String studentInput) {
        if (val != null)
            return val.equalsIgnoreCase(**studentInput.replaceAll("\\s+","")**);
        else return false;
    }
The bold part means any input with spaces between them is automatically shrunk, so input like "8 6/8" becomes 86/8 and hence becomes unequal to stored value.
