### ISSUE TITLE
Class Summary Per Common Core Cluster --Clicking on a problem name

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#34]
In the Class Summary Per Common Core Cluster, it would be ideal to have the same behavior as we have in the Problem Manager, meaning that when you CLICK, you launch the PREVIEW of the problem and can see it clearly.

This should allow for discussions of hard problems, allowing them to be projected in front of the class.

--Ivon

**Comment by nsmenon** [comment]
Fixed. Will be available by 2/12/2019
