### ISSUE TITLE
Tema actual: [is in english]

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#39]
Hi Neeraj:

The topic name, inside of the practice area, is in English still.

It says:  

Tema actual: Decimals and Percents Review  
At the top of the practice area page.

Also, I would change the word: "Diccionario" on the tool bar  to "Habilitar Flash".

Thanks!

--Ivon

**Comment by nsmenon** [comment]
Partly Fixed. The other fix would be available in next release
