### ISSUE TITLE
Spanish problem showing up as an example

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#41]
Neeraj, there is an ugly small bug.
When an example is chosen at the beginning of a topic, maybe the language is not checked?

Try logging in as a guest user to mathspring.org  The first problem you get as an example at the beginning of the first topic is in Spanish (id=1930). 

However, if you do:
select language from problem where id=1930
in either database, the language is set to spanish!

--Ivon

**Comment by nsmenon** [comment]
Fixed. Should be available by next release

**Comment by IvonArroyo** [comment]
Thank you!  --Ivon
-----------
Ivon Arroyo
Associate Professor in Social Sciences and Policy Studies, Computer
Science, Data Science, and Interactive Media & Game Development
P.I. of the Advanced Learning Technologies Lab (http://alt.wpi.edu)
Learning Sciences and Technologies Graduate Program
(https://www.wpi.edu/academics/departments/learning-sciences-technologies)
Salisbury Labs 312
Worcester Polytechnic Institute
-----------
