### ISSUE TITLE
When MSAdmin authored problems play as examples, choices don't show

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#44]
Hi all,
When problem number #1809 shows as an example inside MathSpring, it does not display the answer choices at all, which leaves half of the problem not displayed. 
I wonder if all multiple-choice problems do this also when being shown as examples?

However, when  I see it as a practice problem, it does show the answer choices. 
See the attached screen.

<img width="802" alt="Screen Shot 2019-04-30 at 6 11 29 PM" src="https://user-images.githubusercontent.com/5631787/56996842-d9bd8c80-6b73-11e9-8fd3-bde2023b600c.png">

--Ivon

**Comment by IvonArroyo** [comment]
This problem repeats for all MSAdmin authored problems.
Examples in general are not showing the answer choices.

**Comment by FrankSylvia** [comment]
Moved to new repo as # 12
