### ISSUE TITLE
Complete translation to Spanish inside of Mathspring

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#45]
We need to complete translation to Spanish inside Mathspring.
Because it should be translated by now in full, I consider this a bug.

This involves areas of the Student Progress Page, which are hard-coded right now.

It also involves pop-up boxes at the end of a Topic, when it is mastered, or is moving on to another topic for some reason.

**Comment by IvonArroyo** [comment]
There are several areas:

1. Teacher Tools, in the reports in particular (Class Report Card, in SP is Libreta de la Clase)
2. Some messages in the Student Progress Page are in English (but they are hard coded).
3.  A few windows pop-up as you exit a problem set, and they are all in English, hard-coded).

**Comment by FrankSylvia** [comment]
Moved to new repor as # 10
