### ISSUE TITLE
New Report Per Topic: Student x Problem

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#47]
We should create a new report that, for each topic, has a matrix of  students as rows and problems as columns.

Each cell should have a check if they solved correctly, and a cross if incorrect.

Because of the adaptive nature we should have grey crosses and checks for the problems a student has not reached, suggesting we believe they would have gotten those correct or incrorrect, depending on their difficulty.

**Comment by FrankSylvia** [comment]
This report is very similer to issue #61, the difference being this report would slice the problems up by topic first.  How do we let them choose topics? Accordian would allow viewing one at a time, multi-select dropdown list, something else? If they select all topics, then it is the 'issue #61' report.

**Comment by FrankSylvia** [comment]
Moved to new repo as # 13
