### ISSUE TITLE
Cabin or Comic Sans MS or Trebuchet for problems

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#49]
The font of the problems is just incredibly boring for kids.

Could we change the default font in which HTML problems are rendered in MathSpring to one of there that are more round, and child-friendly? Would it always work in Chrome?

Cabin or Comic Sans MS or Trebuchet

**Comment by IvonArroyo** [comment]
It would just need to be about the same size as what we have, so that the problems that already exist and were created don't take more space than before.

**Comment by FrankSylvia** [comment]
Here is a sample problem.  I see that the word 'Step' needs to be translated.

![ComicSansSerif](https://user-images.githubusercontent.com/46008380/64693679-ce556880-d465-11e9-98c0-36c34de8f041.PNG)

**Comment by IvonArroyo** [comment]
This looks SO much better!!
Yes., the word "Step" needs to be translated to "Paso"

--Ivon

**Comment by IvonArroyo** [comment]
Frank, SPP stands for "Student Progress Page", the My Progress area.

**Comment by FrankSylvia** [comment]
Moved to new repo as # 6
