### ISSUE TITLE
Launching a flash window after login, similar to the Glossary

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#6]
Can we launch a flash window after login, similar to the Glossary? That way, any user is warned that they should enable flash from the beginning.
    - IS this part of a pedagogy (something that happens after login) or about the Core MathSpring?

**Comment by IvonArroyo** [comment]
This one is becoming more important as we hit the schools in January.  It could be part of a pedagogy. You could launch a window that says: Can you see this? at the top and tries to load the Glossary:
http://www.amathsdictionaryforkids.com/dictionary.html

--Ivon

**Comment by nsmenon** [comment]
Sure. I will try to complete this January.

--
Neeraj

**Comment by nsmenon** [comment]
Fixed.
