### ISSUE TITLE
Need a Report for Student x MathQuestion as a matrix

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#61]
Teachers have asked for a report that is a matrix, where each row is a student and each column is a question.

Whenever a student has seen a question, we need a check or a minus (similar to the tiles in the SPP coding) where we can see how students have really done on a single question.

If the student has not seen the question, we should leave it blank for the time being. In the future we should make an estimation of whether the student would answer it correctly or not.

**Comment by FrankSylvia** [comment]
Questions:
All students in all classes? Sorted by class?
What does SPP stand for?

**Comment by IvonArroyo** [comment]
Naa, this is anooother report for the class. It involves only the students in the class that the report is running for only.

This would be another report in the "Class Report Card", just like "Class Summary Per Common Core" for instance.

**Comment by FrankSylvia** [comment]
Moved to nee repo as # 7
