### ISSUE TITLE
Teacher tools: manage problem sets: accordion V doesn't open

### ISSUE THREAD

**Issue by IvonArroyo** [nsmenon/mathspring-V2#63]
<img width="1278" alt="Screen Shot 2019-09-09 at 5 40 34 PM" src="https://user-images.githubusercontent.com/5631787/64570401-e7abc700-d336-11e9-8f0f-25c4d3164b02.png">

Teacher tools: manage problem sets: accordion for "multiplication/division of fractions"  (or is it alwats for the last topic in the list?) doesn't open to reveal the problems for that topic.

To test this, you may look at this class, or create a class with "Multiplication/.Division of Fractions" as part of the topics list.

**Comment by FrankSylvia** [comment]
Estimating effort.

**Comment by FrankSylvia** [comment]
Moved to repo as issue 5
